version: '2'
services:
  gestalt:
    build: .
    volumes:
      - "./screenshots:/app/screenshots"
      - "./dist:/app/packages/gestalt/dist"
    environment:
      - BUILDKITE
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PARALLEL_JOB_COUNT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - CI
      - DANGER_GITHUB_API_TOKEN